config/routes.rb
Vegan::Application.routes.draw do
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  #  mount Spree::Core::Engine, :at => '/'
  root to: 'spree/user_registrations#new', as: '/'

  #constraints subdomain: false do
  #get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
  #end

  resources :statics do
    collection do
      get :aboutus
      get :snacks
      get :contactus
      get :faq
      get :membership
      get :snack_detail
      get :individual_product
      get :privacy_policy
      get :term_conditions
    end
  end

  resources :api , except:[:destroy, :edit, :update, :create, :new] do
    collection do
      post :orders_placed
      post :add_shipments
      post :update_shipments
      get  :subscription_charged
      post :subscription_charged
      get  :subscription_charge_error
      post :subscription_charge_error
    end
  end

  mount Spree::Core::Engine, at: '/spree'
  mount Ckeditor::Engine => '/ckeditor'

  resources :users do
    collection do
      get :profile
      post :update_account
      post :update_address
      post :update_password
      post :new_address
      get :new_billing_address
      post :billing_address
      get :edit_address
      post :fetch_address
      post :remove_address
      get :new_acc_address
      post :create_acc_address

      post :pause
      post :resume
    end
  end

  resources :my_subscriptions do
    collection do
      get :create_new_subscription
      get :prompt_cancelation
      get :prompt_confirmation_modal
      #post :pause
      post :resume
      #post :submit_cancel
      post :fetch_subscriptions_payment
      post :unblock
      get :fetch_used_card
    end
    member do
      get :cancel
      post :submit_cancel
      #post :resume
      post :pause
      post :block
    end
  end

  resources :subscriptions do
    collection do
      post :place
    end
  end

  resources :creditcards , except: [:destroy, :edit,  :update, :create, :new] do
    collection do
     post :newcard
      post :confirm_payment
      post :add_card_complete_payment
      post :pay
    end
    member do
      post :update
    end
  end

  resources :cart_items do
    collection do
      post :name
    end
  end

  resources :carts do
    collection do
      post :add
      post :add_snack_to_queue
      get :my_cart
      post :remove_item
      post  :update_cart
      get :update_cart
      post :change_subscription_type
      post :place_subscription
      post :new_subscription
      get :new_cart
      post :get_notification
      post :check_cart_status

    end
  end


  authenticated :users do
    root to: 'sers#profile'
  end

  resources :tags
  resources :comments

  resources :posts,  only: [:index, :show] do
    resources :comments
    collection do
      post :get_tag_details
      get :get_latest_blogpost
    end
  end


  get "/snack_list", to: 'spree/products#snack_list'
  get "/snack_show", to: 'spree/products#snack_show'
  # get "/snack_detail", to: 'spree/products#list_products'

  authenticated :user do
    root to: 'user#show', as: :authenticated_root
  end

  devise_scope :spree_user do
    get 'users/auth/:provider/callback' => 'spree/user_registrations#new_facebook_signup'
    #get 'users/auth/:provider/callback' => 'spree/user_registrations#new'
    post '/fb_auth' => 'spree/user_registrations#create_facebook_auth_user'
    post '/save_newsletter' => 'spree/user_registrations#save_newsletter'
    get '/check_email' => 'spree/user_registrations#check_email'
    get '/wizard_new' => 'spree/user_registrations#wizard_new'
    get '/check_phone_no_format', to: 'spree/user_registrations#check_phone_no_format'
    get :admin, :to => 'spree/user_sessions#new'
  end

  resources :images do
    collection do
      post :image_link
    end
  end


  Spree::Core::Engine.routes.draw do
    resources :orders, except: [:new, :create, :destroy] do
      collection do
        get :snack_queue
        get :update_subscription
        get :my_subscription
        post :change_subscription_type
        post :place_subscription
        post :check_order_completed
        post :order_placed, :to => 'orders#order_placed'
        get :confirm
        post :edit_snack_queue
        post :update_snack_queue
        get :get_card
      end
    end

    resources :products do
      collection do
        post :product_details
        # get :list_products
      end
    end
  end
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      # get '/spree/admin/vendors', to: 'spree/admin/vendors#index', as: 'vendors'

      resources :blogs
      #get '/spree/admin/vendors', to: 'spree/admin/vendors#index'
      # get '/spree/admin/blogs', to: 'spree/admin/blogs#index'
      resources :password
      resources :subscriptions

      resources :coupons do
        collection do
          get :check_valid_coupon
          post :generate_coupon
        end
      end
      resources :orders do
        collection do
          post :export
          get :range
        end

      end
        resources :vendors, as: 'vendors'
    end
  end

end

app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
Spree::Admin::Orders::CustomerDetailsController.class_eval do
    include CustomerDetailsHelper

    def update
        @order.bill_address.assign_attributes(order_params[:bill_address_attributes])
        @order.ship_address.assign_attributes(order_params[:ship_address_attributes])

        if @order.save
            @order.update_total_and_item_total
            flash[:success] = Spree.t('customer_details_updated')
            redirect_to admin_order_customer_path(@order)
        else
            @order.errors.messages.each do |_,v|
                v.delete( "can't be blank" )
            end
            render :action => :edit
        end

    end

end

app/views/spree/admin/orders/_add_product.html.erb
<%= render :partial => "spree/admin/variants/autocomplete", :formats => :js %>
<%= render :partial => "spree/admin/variants/autocomplete_stock", :formats => :js %>

<div id="add-line-item" data-hook>
  <fieldset class="no-border-bottom">
    <legend align="center"><%= Spree.t(:snacks) %></legend>

    <div data-hook="add_product_name" class="field twelve columns alpha">
      <%#= label_tag :add_variant_id, Spree.t(:name_or_sku) %>
      <%= label_tag :snacks_list, "Order includes below snacks : " %>
      <%= hidden_field_tag :add_variant_id, "", :class => "variant_autocomplete fullwidth" %>
    </div>

  </fieldset>

  <div id="stock_details"></div>
</div>

app/views/spree/admin/orders/_filter_form.html.erb
  <%= form_tag spree.range_admin_orders_path, method: :get, id: 'form_filter' do |f|%>

  <div>
  <%= label_tag 'Filter on basis of :' %>
    <div>
      <%= select :date, :types, ["Delivery Date", "Order Date"], :id => 'user_subscription_list' %>
     </div>
  </div>

  <div>
    <%= text_field_tag :start_range, nil, id: 'date_start',
        class: 'order-datepicker', placeholder: 'Select start date', readonly: true %>

    <%= text_field_tag :end_range, nil, id: 'date_end',
        class: 'order-datepicker', placeholder: 'Select end date', readonly: true %>
  </div>

  <div id="filter_export">
    <div id="filter_result"></div>
    <%= submit_tag  'Filter orders', class: 'filter-btn', id: 'filter_submit' %>
    <%= link_to 'reset filter', '/spree/admin/orders', class: 'filter-btn' %>
  </div>

  <%= submit_tag 'Generate report', id: "export_submit" if @orders.present? %>

  <% end %>

app/views/spree/admin/orders/_form.html.erb
<div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
      <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @line_item } %>
  <% end %>

  <%# if Spree::Order.checkout_step_names.include?(:delivery) %>
      <%#= render :partial => "spree/admin/orders/shipment", :collection => @order.shipments, :locals => { :order => order } %>
  <%# else %>
      <%= render :partial => "spree/admin/orders/line_items", :locals => { :order => order } %>
  <%# end %>
  <% if order.adjustments.eligible.exists? %>
      <fieldset class="no-border-bottom">
        <legend><%= Spree.t('adjustments') %></legend>
        <table>
          <thead>
          <th><%= Spree.t('name')%></th>
          <th><%#= Spree.t('amount')%></th>
          </thead>
          <tbody id="order-charges" data-hook="order_details_adjustments"  class="with-border">
          <% order.adjustments.eligible.each do |adjustment| %>
              <% next if ((adjustment.originator_type == 'Spree::TaxRate') and (adjustment.amount == 0)) || adjustment.originator_type == 'Spree::ShippingMethod' %>
              <tr class="total">
                <td><strong><%= adjustment.label %>:</strong></td>
                <td class="total align-center"><span><%= adjustment.display_amount %></span></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </fieldset>
  <% end %>

  <% if order.line_items.exists? %>
      <fieldset class="no-border-bottom" id="order-total" data-hook="order_details_total">
        <legend><%= Spree.t(:order_total) %></legend>
        <span class="order-total"><%= Spree::Order.where(id: order.id).first.total.to_f %></span>
      </fieldset>
  <% end %>

  <% if @order.payments.exists? %>
      <%= render 'spree/admin/orders/risk_analysis', latest_payment: @order.payments.order("created_at DESC").first %>
  <% end %>

  <%= javascript_tag do -%>
      var order_number = '<%= @order.number %>';
      var shipments = [];

      <% @order.shipments.each do |shipment| %>
          shipments.push(<%== shipment.to_json(:root => false, :include => [:inventory_units, :stock_location]) %>);
      <% end %>

      <%= render :partial => 'spree/admin/shared/update_order_state', :handlers => [:js] %>
  <% end -%>
</div>

app/views/spree/admin/orders/_line_items.html.erb
<% if order.line_items.exists? %>
    <table class="line-items index" data-hook="line-items">
      <colgroup>
        <col style="width: 10%;" />
        <col style="width: 20%;" />
        <col style="width: 20%;" />
        <col style="width: 15%;" />
      </colgroup>

      <thead>
      <th colspan="2"><%= Spree.t(:name) %></th>
      <!--<th><%#= Spree.t(:price) %></th>-->
      <th><%= Spree.t(:quantity) %></th>
      <!--<th><%#= Spree.t(:total_price) %></th>-->
      <th class="orders-actions actions" data-hook="admin_order_form_line_items_header_actions">&nbsp;</th>
      </thead>

      <tbody>
      <% order.line_items.each do |item| %>

          <tr class="line-item" id="line-item-<%= item.id %>">
            <td class="line-item-image"><%= mini_image(item.variant) %></td>
            <td class="line-item-name">
              <%= item.variant.product.name %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
            </td>
            <!--<td class="line-item-price align-center"><%#= item.single_money.to_html %></td>-->
            <td class="line-item-qty-show align-center">
              <%= item.quantity %>
            </td>
            <td class="line-item-qty-edit hidden">
              <%= number_field_tag :quantity, item.quantity, :min => 0, :class => "line_item_quantity", :size => 5 %>
            </td>
            <!--<td class="line-item-total align-center"><%#= line_item_shipment_price(item, item.quantity) %></td>-->
            <td class="cart-line-item-delete actions" data-hook="cart_line_item_delete">
              <% if can? :update, item %>
                  <%#= link_to '', '#', :class => 'save-line-item icon_link icon-ok no-text with-tip', :data => { 'line-item-id' => item.id, :action => 'save'}, :title => Spree.t('actions.save'), :style => 'display: none' %>
                  <%#= link_to '', '#', :class => 'cancel-line-item icon_link icon-cancel no-text with-tip', :data => {:action => 'cancel'}, :title => Spree.t('actions.cancel'), :style => 'display: none' %>
                  <%#= link_to '', '#', :class => 'edit-line-item icon_link icon-edit no-text with-tip', :data => {:action => 'edit'}, :title => Spree.t('edit') %>
                  <%#= link_to '', '#', :class => 'delete-line-item icon-trash no-text with-tip', :data => { 'line-item-id' => item.id, :action => 'remove'}, :title => Spree.t('delete') %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/spree/admin/orders/_order_list.html.erb
<div class="order-pages">
  <%= paginate @orders %>
</div>
<% if @orders.present? %>
  <table class="index responsive" id="listing_orders" data-hook>
    <colgroup>

      <col style="width: 13%;">
      <col style="width: 20%;">
      <col style="width: 20%;">
      <col style="width: 12%;">
      <col style="width: 12%;">
      <col style="width: 25%;">
      <col style="width: 10%;">
      <col style="width: 20%;">

    </colgroup>
    <thead>
    <tr data-hook="admin_orders_index_headers" id="order_column">
    <th><%= sort_link @search, :number, I18n.t(:number, :scope => 'activerecord.attributes.spree/order') %></th>
      <% if @show_only_completed %>
        <th><%= sort_link @search, :completed_at, I18n.t(:completed_at, :scope => 'activerecord.attributes.spree/order') %></th>
      <% else %>
        <th><%= sort_link @search, :created_at, I18n.t(:created_at, :scope => 'activerecord.attributes.spree/order') %></th>
      <% end %>

      <th> <%= sort_link @search, :delivery_date, 'Delivery Date' %> </th>
      <th><%= sort_link @search, :lockdown_date, 'Lockdown Date' %> </th>
      <th><%= sort_link @search, :state,  I18n.t(:state, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :payment_state, I18n.t(:payment_state, :scope => 'activerecord.attributes.spree/order') %></th>
      <% if Spree::Order.checkout_step_names.include?(:delivery) %>
        <th><%= sort_link @search, :shipment_state, I18n.t(:shipment_state, :scope => 'activerecord.attributes.spree/order') %></th>
      <% end %>
      <th><%= sort_link @search, :email,  I18n.t(:email, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :total,  I18n.t(:total, :scope => 'activerecord.attributes.spree/order') %></th>
      <th><%= sort_link @search, :subscription, " Subscription   " %> </th>
      <th data-hook="admin_orders_index_header_actions" class="actions"></th>
    </tr>
    </thead>
    <tbody>
<% end %>

<% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
      <td class="align-center"><%= link_to order.number, edit_admin_order_path(order), target: "_blank" %></td>
        <td class="align-center">
        <%#= l (@show_only_completed ? order.completed_at : order.created_at).to_date %>

        <%= order.created_at.strftime("%m-%d-%Y") %>
        </td>

        <td class="align-center"><%= order.delivery_date.strftime("%m-%d-%Y")%></td>

        <td class="align-center"><%= lockdown_date(order.delivery_date) %></td>

        <td class="align-center"><span class="state <%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span></td>
        <td class="align-center">
          <span class="state <%= order.payment_state %>">
          <%#= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %>
          <%= Spree.t("payment_states.#{order.payment_state}")  if order.payment_state %>
          </span>
          </td>
        <% if Spree::Order.checkout_step_names.include?(:delivery) %>
          <td class="align-center"><span class="state <%= order.shipment_state %>"><%= Spree.t("shipment_states.#{order.shipment_state}") if order.shipment_state %></span></td>
        <% end %>
        <td><%= mail_to order.email %></td>
        <td class="align-center"><%= order.display_total.to_html %></td>
        <td class='align-center big-box'>
        <%= order.user_subscription.present? ? order.subscription.subscription_type : 'Not found' %></td>
        <td class='actions align-center' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true %>
        </td>
      </tr>
    <% end %>



    </tbody>
  </table>

  <div class="order-pages">
    <%= paginate @orders %>
    </div>


<% if @orders.blank? %>
  <!-- <div id='no_result'> Sorry, No results found.</div> -->
<% end %>

app/views/spree/admin/orders/_shipment.html.erb
<div id="<%= "shipment_#{shipment.id}" %>">
  <%= render :partial => "spree/admin/variants/split", :formats => :js %>
  <fieldset class="no-border-bottom">
    <legend align="center" class="stock-location" data-hook="stock-location">
      <span class="shipment-number"><%= shipment.number %></span>
      -
      <span class="shipment-state"><%= Spree.t("shipment_states.#{shipment.state}") %></span>
      <%= Spree.t(:package_from) %>
      <!-- <strong class="stock-location-name" data-hook="stock-location-name">'<%#= shipment.stock_location.name %>'</strong> -->
      <% if shipment.ready? and can? :update, shipment %>
        -
        <%= link_to Spree.t(:ship), '#', :class => 'ship button icon-arrow-right', :data => {'shipment-number' => shipment.number} %>
      <% end %>
    </legend>
  </fieldset>

  <table class="stock-contents index" data-hook="stock-contents">
    <colgroup>
      <col style="width: 10%;" />
      <col style="width: 30%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
      <col style="width: 15%;" />
    </colgroup>

    <thead>
      <th colspan="2"><%= Spree.t(:item_description) %></th>
      <th><%= Spree.t(:price) %></th>
      <th><%= Spree.t(:quantity) %></th>
      <th><%= Spree.t(:total) %></th>
      <th class="orders-actions actions" data-hook="admin_order_form_line_items_header_actions"></th>
    </thead>

    <tbody data-shipment-number="<%= shipment.number %>" data-order-number="<%= order.number %>">
      <%= render 'spree/admin/orders/shipment_manifest', order: order, shipment: shipment %>

      <% unless shipment.shipped? %>
        <tr class="edit-method hidden total">
          <td colspan="5">
            <div class="field alpha five columns">
              <%= label_tag 'selected_shipping_rate_id', Spree.t(:shipping_method) %>
              <%= select_tag :selected_shipping_rate_id,
                    options_for_select(shipment.shipping_rates.map {|sr| ["#{sr.name} #{sr.display_price}", sr.id] }, shipment.selected_shipping_rate_id),
                    {:class => 'select2 fullwidth', :data => {'shipment-number' => shipment.number } } %>
            </div>

            <% if shipment.adjustment && shipment.adjustment.closed? %>
              <div class="field omega four columns">
                <label><%= Spree.t(:associated_adjustment_closed) %></label>
                <ul>
                  <li><%= radio_button_tag :open_adjustment, 'yes', false, data: { 'shipment-number' => shipment.number } %> <%= Spree.t(:say_yes) %></li>
                  <li><%= radio_button_tag :open_adjustment, 'no', true, data: { 'shipment-number' => shipment.number } %> <%= Spree.t(:say_no) %></li>
                </ul>
              </div>
            <% end %>
          </td>
          <td class="actions">
            <% if can? :update, shipment %>
              <%= link_to '', '#', :class => 'save-method icon_link icon-ok no-text with-tip',
                :data => {'shipment-number' => shipment.number, :action => 'save'}, title: Spree.t('actions.save') %>
              <%= link_to '', '#', :class => 'cancel-method icon_link icon-cancel no-text with-tip',
                :data => {:action => 'cancel'}, :title => Spree.t('actions.cancel') %>
            <% end %>
          </td>
        </tr>
      <% end %>

      <tr class="show-method total">
        <td colspan="4">
          <% if shipment.adjustment.present? && shipment.shipping_method.present? %>
            <strong><%= shipment.adjustment.label %>: <%= shipment.shipping_method.name %></strong>
          <% else %>
            <%= Spree.t(:cannot_set_shipping_method_without_address) %>
          <% end %>
        </td>
        <td class="total" align="center">
          <% if shipment.adjustment.present? %>
            <span><%= shipment.adjustment.display_amount %></span>
          <% end %>
        </td>
        <% if shipment.adjustment.present? && !shipment.shipped? %>
          <td class="actions">
            <% if can? :update, shipment %>
              <%= link_to '', '#', :class => 'edit-method icon_link icon-edit no-text with-tip', :data => {:action => 'edit'}, :title => Spree.t('edit') %>
            <% end %>
          </td>
        <% end %>
      </tr>

      <tr class="edit-tracking hidden total">
        <td colspan="5">
          <label><%= Spree.t(:tracking_number) %>:</label>
          <%= text_field_tag :tracking, shipment.tracking %>
        </td>
        <td class="actions">
          <% if can? :update, shipment %>
            <%= link_to '', '#', :class => 'save-tracking icon_link icon-ok no-text with-tip', :data => {'shipment-number' => shipment.number, :action => 'save'}, :title => Spree.t('actions.save') %>
            <%= link_to '', '#', :class => 'cancel-tracking icon_link icon-cancel no-text with-tip', :data => {:action => 'cancel'}, :title => Spree.t('actions.cancel') %>
          <% end %>
        </td>
      </tr>

      <% if @order.special_instructions.present? %>
        <tr class='special_instructions'>
          <td colspan="5">
            <strong><%= Spree.t(:special_instructions) %>:&nbsp;</strong><%= @order.special_instructions %>
          </td>
        </tr>
      <% end %>

      <tr class="show-tracking total">
        <td colspan="5">
          <% if shipment.tracking.present? %>
            <strong><%= Spree.t(:tracking) %>:</strong> <%= shipment.tracking %>
          <% else %>
            <%= Spree.t(:no_tracking_present) %>
          <% end %>
        </td>
        <td class="actions">
          <% if can? :update, shipment %>
            <%= link_to '', '#', :class => 'edit-tracking icon_link icon-edit no-text with-tip', :data => {:action => 'edit'}, :title => Spree.t('edit') %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/spree/admin/orders/edit.html.erb
<%= csrf_meta_tags %>
<% content_for :page_actions do %>
    <% if can?(:fire, @order) %>
        <li><%#= event_links %></li>
    <% end %>
    <% if can?(:resend, @order) %>
        <li><%#= button_link_to Spree.t(:resend), resend_admin_order_url(@order), :method => :post, :icon => 'icon-email' %></li>
    <% end %>
    <% if can?(:admin, Spree::Order) %>
        <li><%= button_link_to Spree.t(:back_to_orders_list), admin_orders_path, :icon => 'icon-arrow-left' %></li>
    <% end %>
<% end %>

<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>

<div data-hook="admin_order_edit_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
</div>

<%= render :partial => 'add_product' if can?(:update, @order) %>

<% if @order.line_items.empty? %>
    <div class="no-objects-found">
      <%= Spree.t(:your_order_is_empty_add_product)%>
    </div>
<% end %>

<div data-hook="admin_order_edit_form">
  <div id="order-form-wrapper">
    <%= render :partial => 'form', :locals => { :order => @order } %>
  </div>
</div>

<% content_for :head do %>
    <%= javascript_tag 'var expand_variants = true;' %>
<% end %>

app/views/spree/admin/orders/export.xls.erb
<table border="1">
  <tr>
    <th> Number</th>
    <th>Order date</th>
    <th>Delivery Date</th>
    <th>Lockdown Date</th>
    <th>state</th>
    <th>payment state</th>
    <th>shipment state</th>
    <th>Customer Email</th>
    <th>total</th>
    <th> subscription </th>

  </tr>

  <% @orders.each do |order| %>
  <tr>
    <td> <%= order.number %> </td>
    <td> <%= order.created_at.strftime("%m-%d-%Y") %> </td>
    <td> <%= order.delivery_date.strftime("%m-%d-%Y") %> </td>
    <td>  <%= lockdown_date(order.delivery_date) %></td>
    <td> <%= order.state %> </td>
    <td> <%= order.payment_state %> </td>
    <td> <%= order.shipment_state %> </td>
    <td> <%= order.email %> </td>
    <td> <%= order.total.to_f %> </td>
    <td>
    <%=  order.user_subscription.present? ? order.user_subscription.subscription.subscription_type : 'Not found' %>
    </td>

  </tr>
  <% end %>
</table>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_orders) %>
<% end %>

<div id="order_page">
    <%= render :partial => "filter_form"%>
  <div id='order_range'>
      
  </div>

  <% if @orders.any? %>
    <div id="orders_list">
      <%= render :partial => "order_list" %>
    </div>

  <% else %>
    <div class="alpha twelve columns no-objects-found">
      <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/order')) %>!
  </div>
  <% end %>

</div>

app/views/spree/admin/orders/index.js.erb
$("#orders_list").html("<%= escape_javascript(render 'order_list') %>");
add_ajax_to_links();

app/views/spree/admin/orders/range.js.erb
<% if @start_date.present? && @end_date.present? %>

    <% if @orders.present? %>
        <% result = "Total #{@orders.count} orders were found between #{pretty_time(@start_date)} and #{pretty_time(@end_date)}. (Filtered on #{@date_type})" %>
        <% app_class = 'range-success' %>
    <% else %>
        <% result = "Sorry, No results found." %>
        <% app_class = 'range-error' %>
    <% end %>

<% else %>
    <% result = "Select a Date range first." %>
    <% app_class = 'range-error' %>
<% end %>

$("#orders_list").html("<%= escape_javascript(render 'order_list') %>");
$("#order_range").html("<%= escape_javascript(render 'filter_form') %>");

load_calendar();
reset_form_for_export();
reset_form_for_filteration();

set_date_ranges("<%= @start_date_params %>", "<%= @end_date_params %>");

$("#filter_result").text("<%= result %>");
$("#filter_result").removeClass().addClass("<%= app_class %>");
add_ajax_to_links();